### PR TITLE
Refresh the authentication token if it expires during the download

### PR DESCRIPTION
**Pull request by Jan-Magerl**
#26

### CODE REVIEW

**Comment by tpill90** [comment]
@Jan-Magerl Did you mean to close this?

**Comment by Jan-Magerl** [comment]
@tpill90 not working yet, i forgot to update the httpclient header

**Comment by tpill90** [comment]
👍  I'm going to reopen this. Just comment when it's ready and I'll review

**Comment by Jan-Magerl** [comment]
It's ready

**Review by tpill90 — APPROVED** [review]

**Comment by tpill90** [comment]
Approved and merged!  Thank you!  I'll get this released shortly

**Pull request merged**
